import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import {
  SignIn,
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        {/* [[...index]].tsx */}
        {/* <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}
        {/* <SignInButton />
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}
        <SignedIn>
          {/* Mount the UserButton component */}

          {/* <UserButton /> */}
          <SignOutButton />
        </SignedIn>

        <SignedOut>
          {/* Signed out users get sign in button */}

          <SignInButton />
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
